Created the footer and newsletter
Gabriel0508/Ng-Food-Recipe-App pull request #23
Opened 2023-03-16 10:26 UTC by Gabriel0508

**Developed by:**

-created the footer
-created the newsletter

![image](https://user-images.githubusercontent.com/65502252/225588768-8f1df979-7820-4430-b088-4784d0344482.png)

2023-03-16 15:10 UTC, alexPopNicolae requested changes

2023-03-16 15:10 UTC, alexPopNicolae commented on src/app/pages/newsletter/newsletter/newsletter.component.html
> +        </span>
this should be abstracted in a single message as we did on the register form.

2023-03-16 15:10 UTC, alexPopNicolae commented on src/app/pages/newsletter/newsletter/newsletter.component.html
> +          *ngIf="(newsletterForm.controls['email'].touched || newsletterForm.controls['email'].dirty) && newsletterForm.controls['email'].errors?.['required']"
this should be abstracted in a single message as we did on the register form.

2023-03-16 15:10 UTC, alexPopNicolae commented on src/app/shared/footer/footer.component.scss
> +        font-family: "Open Sans";
asta ar trebui scris asa

font-family: Open-sans;

de asta nu iti arata ca in design

"Open Sans" nu e la fel ca Open-sans - asta pentru ca noi l-am definit intr-un font face

2023-03-16 15:10 UTC, alexPopNicolae commented on src/app/shared/footer/footer.component.scss
> +          font-family: "Open Sans";
acelasi lucru ca mai sus legat de fonturi - foloseste Open-sans

2023-03-16 15:10 UTC, alexPopNicolae commented on src/app/pages/newsletter/newsletter/newsletter.component.scss
> +      font-family: "Open Sans";
foloseste Open-sans

2023-03-16 15:10 UTC, alexPopNicolae commented on src/app/pages/newsletter/newsletter/newsletter.component.scss
> +        font-style: normal;
si aici tot la fel legat de font

2023-03-16 15:10 UTC, alexPopNicolae commented on src/app/pages/newsletter/newsletter/newsletter.component.scss
> +        font-family: "Open Sans";
acelasi lucru legat de font

2023-03-16 15:10 UTC, alexPopNicolae commented on src/app/pages/landing/landing.module.ts
> +    NewsletterModule
newsletterul nu e o componenta asa de mare ... si ar trebui pusa in shared module...
nu are nevoie de propriul modul - pune componenta impreuna cu restul in shared module

2023-03-16 15:10 UTC, alexPopNicolae commented on src/app/pages/newsletter/newsletter/newsletter.component.scss
> +      font-family: "Open Sans";
schimba fontul

2023-03-16 15:32 UTC, Gabriel0508 commented on src/app/pages/newsletter/newsletter/newsletter.component.html
> +        </span>
done

2023-03-16 15:32 UTC, Gabriel0508 commented on src/app/pages/newsletter/newsletter/newsletter.component.html
> +          *ngIf="(newsletterForm.controls['email'].touched || newsletterForm.controls['email'].dirty) && newsletterForm.controls['email'].errors?.['required']"
done

2023-03-16 15:32 UTC, Gabriel0508 commented on src/app/shared/footer/footer.component.scss
> +        font-family: "Open Sans";
done

2023-03-16 15:32 UTC, Gabriel0508 commented on src/app/pages/newsletter/newsletter/newsletter.component.scss
> +      font-family: "Open Sans";
done

2023-03-16 15:33 UTC, Gabriel0508 commented on src/app/pages/newsletter/newsletter/newsletter.component.scss
> +        font-family: "Open Sans";
done

2023-03-16 15:33 UTC, Gabriel0508 commented on src/app/pages/newsletter/newsletter/newsletter.component.scss
> +      font-family: "Open Sans";
done

2023-03-16 15:36 UTC, Gabriel0508 commented on src/app/pages/landing/landing.module.ts
> +    NewsletterModule
done

2023-03-16 16:17 UTC, Gabriel0508 commented on src/app/shared/footer/footer.component.scss
> +          font-family: "Open Sans";
done

2023-03-16 16:18 UTC, Gabriel0508 commented on src/app/pages/newsletter/newsletter/newsletter.component.scss
> +        font-style: normal;
done

2023-03-17 10:50 UTC, merged

2023-03-17 10:51 UTC, alexPopNicolae approved these changes